/** Staleness tripwire + cross-implementation anchor for the committed streaming fixture.
 *
 *  tests/fixtures/stream.webm and stream_depth.u16 are regenerated by hand
 *  (tests/fixtures/regen_stream.mjs) and consumed by the *native* decoder in
 *  tests/test_stream_interop.py. Nothing else checked that the committed bytes still say what
 *  the generator says they should, or that the JS side can read the file at all. This does both:
 *
 *    - stream_depth.u16 must equal the generator's output verbatim;
 *    - the committed WebM must still be the unknown-size / "frames":null streamed layout;
 *    - decoding it through the WASM backend must return exactly the generator's codes.
 *
 *  A regeneration that changes the payload, or an encoder change that alters the container,
 *  fails here rather than silently drifting away from the Python test's expectations.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { demux } from '../src/webm.js';
import { createDecoder } from '../src/chromapakz.js';
import { W, H, N, makeSequence, flatSequence } from './fixtures/stream_fixture.mjs';

const HERE = new URL('./fixtures/', import.meta.url);
const webm = new Uint8Array(readFileSync(new URL('stream.webm', HERE)));
const rawU16 = readFileSync(new URL('stream_depth.u16', HERE));

test('stream_depth.u16 still matches the fixture generator', () => {
  const expected = flatSequence();
  assert.equal(rawU16.length, expected.length * 2, 'byte length (N*W*H uint16 LE)');
  const got = new Uint16Array(rawU16.buffer, rawU16.byteOffset, expected.length);
  assert.ok(got.every((v, i) => v === expected[i]),
    'stream_depth.u16 is stale — re-run node tests/fixtures/regen_stream.mjs');
});

test('stream.webm is still a streamed, unknown-size file', () => {
  const d = demux(webm);
  assert.equal(d.metadata.version, 2);
  assert.equal(d.metadata.frames, null, 'streamed header carries frames:null');
  assert.equal(d.metadata.streaming, true);
  assert.equal(d.metadata.width, W);
  assert.equal(d.metadata.height, H);
  assert.deepEqual(d.metadata.signals.map(s => s.id), ['depth', 'objectId']);
  assert.deepEqual(Object.keys(d.tracks).map(Number).sort((a, b) => a - b), [1, 2, 3, 4]);
  // two signals x (hi, lo) x N frames — the frame count only exists as blocks
  assert.equal(d.frames.length, 4 * N, 'block count');
});

test('stream.webm decodes to the generator codes through the WASM backend', async () => {
  const seq = makeSequence();
  const dec = createDecoder(webm, { backend: 'wasm' });
  const frames = [];
  for await (const fr of dec) frames.push(fr);
  await dec.close();

  assert.equal(frames.length, N, 'decoded frame count');
  for (let i = 0; i < N; i++) {
    for (const sid of ['depth', 'objectId']) {
      const got = frames[i].signals[sid].u16;
      assert.ok(got.every((v, k) => v === seq[i][k]),
        `frame ${i} signal ${sid} is not bit-exact — fixture and generator disagree`);
    }
  }
});
